spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_ssh?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  tomcat:
    max-connections: 200
    threads:
      max: 100
      min-spare: 10
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: INFO
    com.example.web ssh: DEBUG
  file:
    name: logs/web ssh.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# ?????
webssh:
  ssh:
    connection-timeout: 30000
    session-timeout: 1800000
    max-connections-per-user: 10
  file:
    upload-max-size: 100MB
    temp-dir: /tmp/webssh-uploads
  collaboration:
    enabled: true
    max-participants: 10
    session-timeout: 3600000spring.application.name=web-ssh
